### ISSUE TITLE
약속 요청 기능 구현

### ISSUE THREAD

**Issue by gahyeonn** [manyaak/manyaak-back#9]
## 👩‍💻 Summary
약속 요청 API 구현

## 📄 Description
약속을 요청하는 API를 구현합니다.
인원에 상관없이 약속은 모두 클럽으로 관리됩니다. 
기존 클럽원끼리 약속을 잡을 수도 있고, 새로운 클럽을 생성할 수도 있습니다.
 
## ✅ Todo

- [x] 클럽이 없는 경우, 새로 클럽을 생성
- [x] 클럽이 존재하는 경우, 해당 클럽 사용
- [x] model validation
- [x] 약속 테이블에 owner 칼럼, 위치 정보 칼럼 추가
